// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHamf60rf2bAGv87gmv5bBPn6T8twpNfc',
    appId: '1:634669023130:android:789413516398d084f50423',
    messagingSenderId: '634669023130',
    projectId: 'therosary-92ab7',
    databaseURL: 'https://therosary-92ab7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'therosary-92ab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0oAGmxlO8gy6r6BSQeyLFWVIhnHOEsMQ',
    appId: '1:634669023130:ios:b8dace31616ecc43f50423',
    messagingSenderId: '634669023130',
    projectId: 'therosary-92ab7',
    databaseURL: 'https://therosary-92ab7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'therosary-92ab7.appspot.com',
    iosClientId: '634669023130-gej4004j45qnkfu84qondno1slnn94ft.apps.googleusercontent.com',
    iosBundleId: 'com.KahoziJunior.mysteres',
  );
}
