# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Increment Version code

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Analyze
        run: flutter pub get && flutter analyze .
        
      - name: Increment Version
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: android/app/build.gradle
          versionCode: ${{github.run_number}}
          versionName: 1.0.0
          
      - name: Build App Bundle
      - uses: subosito/flutter-action@v1
      - run: flutter build appbundle --dart-define ${{secrets.AD_BANNER_ANDROID_UNIT_ID} --dart-define ${{secrets.AD_BANNER_IOS_UNIT_ID}} --dart-define ${{secrets.AD_INTERSTITIAL_ANDROID_UNIT_ID}} --dart-define ${{secrets.AD_INTERSTITIAL_IOS_UNIT_ID}} --dar-define ${{secrets.FIREBASE_ANDROID_API_KEY}} --dart-define ${{secrets.FIREBASE_ANDROID_APP_ID}} --dart-define ${{secrets.FIREBASE_DATABASE_URL}} --dart-define ${{secrets.FIREBASE_IOS_API_KEY}} --dart-define ${{secrets.FIREBASE_IOS_APP_ID}} --dart-define ${{secrets.FIREBASE_IOS_BUNDLE_ID}} --dart-define ${{secrets.FIREBASE_IOS_CLIENT_ID}} --dart-define ${{secrets.FIREBASE_MESSAGING_SENDER_ID}} --dart-define ${{secrets.FIREBASE_PROJECT_ID}} --dart-define ${{secrets.FIREBASE_STORAGE_BUCKET}} --dart-define ${{secrets.SENTRY_ATTACH_SCREENSHOT}} --dart-define ${{secrets.SENTRY_DSN}}  --dart-define ${{secrets.SENTRY_TRACE_SAMPLE_RATE}}
          
          
          
          
          
